### ISSUE TITLE
Add N-Number and update email page after RSVP

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/rsvp#2]

**Comment by juliepanda** [comment]
If a nNumber field currently doesn't exist in the GET response, can I still PATCH to it? (e.g nNumber)

**Comment by AbhiAgarwal** [comment]
Yes! You can still PATCH it

**Comment by juliepanda** [comment]
I've been trying to PATCH my own profile to add nNumber to `/people/me`:

```
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
{
  "data": {
    "type": "people",
    "id": "544195bba07c236a039e9016",
    "attributes": {
      "nNumber": "N13778510"
    }
  }
}
```

I get this back:
`{"errors":[{"status":"403","title":"Forbidden"}]}`
Do you know how I can solve this?

**Comment by AbhiAgarwal** [comment]
cc @ethanresnick. I'm not too sure why this is happening. I tried doing the same and I get:

```
status: "400"
title: "The id of the resource you provided doesn't match that in the URL."
```

Is the 'id' supposed to be something different? Am I missing something? 

I can't figure this out even after looking at the code-base for a while. I'm jut a little confused how it handles a PATCH on /me. I get how it handles a GET on /me.

**Comment by ethanresnick** [comment]
I'll look into this soon!

**Comment by ethanresnick** [comment]
So, the problem was that the exception that made it easier to access `/people/me` than other `/people/:id` roles was only defined for GET request. I [added](https://github.com/TechAtNYU/api/commit/b3858e0b7bfa63b26c4c7f8df58a0ab26bc5d82b) the same exception for the other routes, and now everything should work perfectly. I backported that change to v2 too. Lmk if there are any other problems!

**Comment by juliepanda** [comment]
Thanks! It works now.

**Comment by AbhiAgarwal** [comment]
:100:
