### ISSUE TITLE
Prepare for SW

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/rsvp#27]
We want to prepare RSVP so we can use it instead of eventbrite for SW. 

Features we want to add:
- Ability to have wait lists on events (cc @ethanresnick - how should we do this?)
- Ability to unrsvp from an event (we can perhaps change the `RSVP'd` button a `unrsvp` or `untick` action.
- Emailing people to confirm that they've signed up for an event (on RSVP action)
- Emailing people to remind that they've signed up for events
- Closing the RSVP 2 days before (needed for Microsoft)

Feel free to chime in @ycp217

**Comment by juliepanda** [comment]
We talked about offline that maybe we can do the following:
- adding `/unrsvp` endpoint to the API
- adding `isClosed` field to Event model

For the waitlist, I can add a `Join the Waitlist` instead of `RSVP` when an event is full (if we add a waitlist to the model).

Although if we have a waitlist and an unRSVP, then we also need:
- to send an email to people when they get off the waitlist to confirm their spot

(after which we add them to the rsvp list? Or we just do that automatically and send them a notice that they are now Rsvp'd to the event?)
