### ISSUE TITLE
Add profile

### ISSUE THREAD

**Issue by juliepanda** [TechAtNYU/rsvp#29]
- skills
- wantsToLearn
- school

**Comment by juliepanda** [comment]
- N-number
- email

**Comment by juliepanda** [comment]
Also now that `rsvpLimit` is a thing on /events on API, add it in instead of using the seats rule from before.

**Comment by AbhiAgarwal** [comment]
@ycp217 I don't think all of the events have that and you can't set that property anymore. I think the information that exists now is just getting it from the Mongo model. I did a rollback on the changes that @brentdur made earlier since they broke some things this morning on the API. We'll definitely add that in as soon as those changes are fixed, though.

So I don't think you should add that to RSVP yet...

**Comment by juliepanda** [comment]
Kk, I saw it on one of the events in upcoming so I wasn't sure.
